/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type StakeInfoStruct = {
  stake: BigNumberish;
  unstakeDelayBlocks: BigNumberish;
  withdrawStake: BigNumberish;
  withdrawBlock: BigNumberish;
};

export type StakeInfoStructOutput = [BigNumber, number, BigNumber, number] & {
  stake: BigNumber;
  unstakeDelayBlocks: number;
  withdrawStake: BigNumber;
  withdrawBlock: number;
};

export type UserOperationStruct = {
  sender: string;
  nonce: BigNumberish;
  initCode: BytesLike;
  callData: BytesLike;
  callGas: BigNumberish;
  verificationGas: BigNumberish;
  preVerificationGas: BigNumberish;
  maxFeePerGas: BigNumberish;
  maxPriorityFeePerGas: BigNumberish;
  paymaster: string;
  paymasterData: BytesLike;
  signature: BytesLike;
};

export type UserOperationStructOutput = [
  string,
  BigNumber,
  string,
  string,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  string,
  string,
  string
] & {
  sender: string;
  nonce: BigNumber;
  initCode: string;
  callData: string;
  callGas: BigNumber;
  verificationGas: BigNumber;
  preVerificationGas: BigNumber;
  maxFeePerGas: BigNumber;
  maxPriorityFeePerGas: BigNumber;
  paymaster: string;
  paymasterData: string;
  signature: string;
};

export interface EntryPointInterface extends utils.Interface {
  functions: {
    "addDeposit()": FunctionFragment;
    "addDepositTo(address)": FunctionFragment;
    "addStake(uint32)": FunctionFragment;
    "create2factory()": FunctionFragment;
    "getPaymastersStake(address[])": FunctionFragment;
    "getSenderAddress(bytes,uint256)": FunctionFragment;
    "getStakeInfo(address)": FunctionFragment;
    "handleOp((address,uint256,bytes,bytes,uint256,uint256,uint256,uint256,uint256,address,bytes,bytes),address)": FunctionFragment;
    "handleOps((address,uint256,bytes,bytes,uint256,uint256,uint256,uint256,uint256,address,bytes,bytes)[],address)": FunctionFragment;
    "internalHandleOp((address,uint256,bytes,bytes,uint256,uint256,uint256,uint256,uint256,address,bytes,bytes),bytes,uint256,uint256,uint8)": FunctionFragment;
    "isContractDeployed(address)": FunctionFragment;
    "isPaymasterStaked(address,uint256)": FunctionFragment;
    "isStaked(address,uint256,uint256)": FunctionFragment;
    "paymasterStake()": FunctionFragment;
    "simulatePaymasterValidation((address,uint256,bytes,bytes,uint256,uint256,uint256,uint256,uint256,address,bytes,bytes),uint256)": FunctionFragment;
    "simulateValidation((address,uint256,bytes,bytes,uint256,uint256,uint256,uint256,uint256,address,bytes,bytes))": FunctionFragment;
    "simulateWalletValidation((address,uint256,bytes,bytes,uint256,uint256,uint256,uint256,uint256,address,bytes,bytes))": FunctionFragment;
    "stakes(address)": FunctionFragment;
    "unlockStake()": FunctionFragment;
    "unstakeDelayBlocks()": FunctionFragment;
    "withdrawStake(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addDeposit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addDepositTo",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "addStake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "create2factory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPaymastersStake",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getSenderAddress",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStakeInfo",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "handleOp",
    values: [UserOperationStruct, string]
  ): string;
  encodeFunctionData(
    functionFragment: "handleOps",
    values: [UserOperationStruct[], string]
  ): string;
  encodeFunctionData(
    functionFragment: "internalHandleOp",
    values: [
      UserOperationStruct,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isContractDeployed",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isPaymasterStaked",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isStaked",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "paymasterStake",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "simulatePaymasterValidation",
    values: [UserOperationStruct, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "simulateValidation",
    values: [UserOperationStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "simulateWalletValidation",
    values: [UserOperationStruct]
  ): string;
  encodeFunctionData(functionFragment: "stakes", values: [string]): string;
  encodeFunctionData(
    functionFragment: "unlockStake",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unstakeDelayBlocks",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawStake",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "addDeposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addDepositTo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addStake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "create2factory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPaymastersStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSenderAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStakeInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "handleOp", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "handleOps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "internalHandleOp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isContractDeployed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPaymasterStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isStaked", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymasterStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "simulatePaymasterValidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "simulateValidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "simulateWalletValidation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stakes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unlockStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unstakeDelayBlocks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawStake",
    data: BytesLike
  ): Result;

  events: {
    "PaymasterPostOpFailed(address,address,uint256,bytes)": EventFragment;
    "StakeAdded(address,uint256,uint256)": EventFragment;
    "StakeUnlocking(address,uint256)": EventFragment;
    "StakeWithdrawn(address,address,uint256)": EventFragment;
    "UserOperationEvent(address,address,uint256,uint256,uint256,bool)": EventFragment;
    "UserOperationRevertReason(address,uint256,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "PaymasterPostOpFailed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StakeAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StakeUnlocking"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StakeWithdrawn"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UserOperationEvent"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UserOperationRevertReason"): EventFragment;
}

export type PaymasterPostOpFailedEvent = TypedEvent<
  [string, string, BigNumber, string],
  { sender: string; paymaster: string; nonce: BigNumber; reason: string }
>;

export type PaymasterPostOpFailedEventFilter =
  TypedEventFilter<PaymasterPostOpFailedEvent>;

export type StakeAddedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  { paymaster: string; totalStake: BigNumber; unstakeDelayBlocks: BigNumber }
>;

export type StakeAddedEventFilter = TypedEventFilter<StakeAddedEvent>;

export type StakeUnlockingEvent = TypedEvent<
  [string, BigNumber],
  { paymaster: string; withdrawBlock: BigNumber }
>;

export type StakeUnlockingEventFilter = TypedEventFilter<StakeUnlockingEvent>;

export type StakeWithdrawnEvent = TypedEvent<
  [string, string, BigNumber],
  { paymaster: string; withdrawAddress: string; amount: BigNumber }
>;

export type StakeWithdrawnEventFilter = TypedEventFilter<StakeWithdrawnEvent>;

export type UserOperationEventEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, BigNumber, boolean],
  {
    sender: string;
    paymaster: string;
    nonce: BigNumber;
    actualGasCost: BigNumber;
    actualGasPrice: BigNumber;
    success: boolean;
  }
>;

export type UserOperationEventEventFilter =
  TypedEventFilter<UserOperationEventEvent>;

export type UserOperationRevertReasonEvent = TypedEvent<
  [string, BigNumber, string],
  { sender: string; nonce: BigNumber; revertReason: string }
>;

export type UserOperationRevertReasonEventFilter =
  TypedEventFilter<UserOperationRevertReasonEvent>;

export interface EntryPoint extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EntryPointInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addDeposit(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addDepositTo(
      target: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addStake(
      _unstakeDelayBlocks: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    create2factory(overrides?: CallOverrides): Promise<[string]>;

    getPaymastersStake(
      paymasters: string[],
      overrides?: CallOverrides
    ): Promise<[BigNumber[]] & { _stakes: BigNumber[] }>;

    getSenderAddress(
      initCode: BytesLike,
      _salt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getStakeInfo(
      paymaster: string,
      overrides?: CallOverrides
    ): Promise<[StakeInfoStructOutput] & { stakeInfo: StakeInfoStructOutput }>;

    handleOp(
      op: UserOperationStruct,
      redeemer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    handleOps(
      ops: UserOperationStruct[],
      redeemer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    internalHandleOp(
      op: UserOperationStruct,
      context: BytesLike,
      preOpGas: BigNumberish,
      prefund: BigNumberish,
      paymentMode: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isContractDeployed(
      addr: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isPaymasterStaked(
      paymaster: string,
      stake: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isStaked(
      paymaster: string,
      requiredStake: BigNumberish,
      requiredDelayBlocks: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    paymasterStake(overrides?: CallOverrides): Promise<[BigNumber]>;

    simulatePaymasterValidation(
      userOp: UserOperationStruct,
      gasUsedByPayForSelfOp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber] & { context: string; gasUsedByPayForOp: BigNumber }
    >;

    simulateValidation(
      userOp: UserOperationStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    simulateWalletValidation(
      userOp: UserOperationStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    stakes(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, number, BigNumber, number] & {
        stake: BigNumber;
        unstakeDelayBlocks: number;
        withdrawStake: BigNumber;
        withdrawBlock: number;
      }
    >;

    unlockStake(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unstakeDelayBlocks(overrides?: CallOverrides): Promise<[number]>;

    withdrawStake(
      withdrawAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addDeposit(
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addDepositTo(
    target: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addStake(
    _unstakeDelayBlocks: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  create2factory(overrides?: CallOverrides): Promise<string>;

  getPaymastersStake(
    paymasters: string[],
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  getSenderAddress(
    initCode: BytesLike,
    _salt: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getStakeInfo(
    paymaster: string,
    overrides?: CallOverrides
  ): Promise<StakeInfoStructOutput>;

  handleOp(
    op: UserOperationStruct,
    redeemer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  handleOps(
    ops: UserOperationStruct[],
    redeemer: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  internalHandleOp(
    op: UserOperationStruct,
    context: BytesLike,
    preOpGas: BigNumberish,
    prefund: BigNumberish,
    paymentMode: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isContractDeployed(addr: string, overrides?: CallOverrides): Promise<boolean>;

  isPaymasterStaked(
    paymaster: string,
    stake: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isStaked(
    paymaster: string,
    requiredStake: BigNumberish,
    requiredDelayBlocks: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  paymasterStake(overrides?: CallOverrides): Promise<BigNumber>;

  simulatePaymasterValidation(
    userOp: UserOperationStruct,
    gasUsedByPayForSelfOp: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber] & { context: string; gasUsedByPayForOp: BigNumber }
  >;

  simulateValidation(
    userOp: UserOperationStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  simulateWalletValidation(
    userOp: UserOperationStruct,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  stakes(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, number, BigNumber, number] & {
      stake: BigNumber;
      unstakeDelayBlocks: number;
      withdrawStake: BigNumber;
      withdrawBlock: number;
    }
  >;

  unlockStake(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unstakeDelayBlocks(overrides?: CallOverrides): Promise<number>;

  withdrawStake(
    withdrawAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addDeposit(overrides?: CallOverrides): Promise<void>;

    addDepositTo(target: string, overrides?: CallOverrides): Promise<void>;

    addStake(
      _unstakeDelayBlocks: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    create2factory(overrides?: CallOverrides): Promise<string>;

    getPaymastersStake(
      paymasters: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    getSenderAddress(
      initCode: BytesLike,
      _salt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getStakeInfo(
      paymaster: string,
      overrides?: CallOverrides
    ): Promise<StakeInfoStructOutput>;

    handleOp(
      op: UserOperationStruct,
      redeemer: string,
      overrides?: CallOverrides
    ): Promise<void>;

    handleOps(
      ops: UserOperationStruct[],
      redeemer: string,
      overrides?: CallOverrides
    ): Promise<void>;

    internalHandleOp(
      op: UserOperationStruct,
      context: BytesLike,
      preOpGas: BigNumberish,
      prefund: BigNumberish,
      paymentMode: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isContractDeployed(
      addr: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isPaymasterStaked(
      paymaster: string,
      stake: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isStaked(
      paymaster: string,
      requiredStake: BigNumberish,
      requiredDelayBlocks: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    paymasterStake(overrides?: CallOverrides): Promise<BigNumber>;

    simulatePaymasterValidation(
      userOp: UserOperationStruct,
      gasUsedByPayForSelfOp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber] & { context: string; gasUsedByPayForOp: BigNumber }
    >;

    simulateValidation(
      userOp: UserOperationStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    simulateWalletValidation(
      userOp: UserOperationStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    stakes(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, number, BigNumber, number] & {
        stake: BigNumber;
        unstakeDelayBlocks: number;
        withdrawStake: BigNumber;
        withdrawBlock: number;
      }
    >;

    unlockStake(overrides?: CallOverrides): Promise<void>;

    unstakeDelayBlocks(overrides?: CallOverrides): Promise<number>;

    withdrawStake(
      withdrawAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "PaymasterPostOpFailed(address,address,uint256,bytes)"(
      sender?: string | null,
      paymaster?: string | null,
      nonce?: null,
      reason?: null
    ): PaymasterPostOpFailedEventFilter;
    PaymasterPostOpFailed(
      sender?: string | null,
      paymaster?: string | null,
      nonce?: null,
      reason?: null
    ): PaymasterPostOpFailedEventFilter;

    "StakeAdded(address,uint256,uint256)"(
      paymaster?: string | null,
      totalStake?: null,
      unstakeDelayBlocks?: null
    ): StakeAddedEventFilter;
    StakeAdded(
      paymaster?: string | null,
      totalStake?: null,
      unstakeDelayBlocks?: null
    ): StakeAddedEventFilter;

    "StakeUnlocking(address,uint256)"(
      paymaster?: string | null,
      withdrawBlock?: null
    ): StakeUnlockingEventFilter;
    StakeUnlocking(
      paymaster?: string | null,
      withdrawBlock?: null
    ): StakeUnlockingEventFilter;

    "StakeWithdrawn(address,address,uint256)"(
      paymaster?: string | null,
      withdrawAddress?: null,
      amount?: null
    ): StakeWithdrawnEventFilter;
    StakeWithdrawn(
      paymaster?: string | null,
      withdrawAddress?: null,
      amount?: null
    ): StakeWithdrawnEventFilter;

    "UserOperationEvent(address,address,uint256,uint256,uint256,bool)"(
      sender?: string | null,
      paymaster?: string | null,
      nonce?: null,
      actualGasCost?: null,
      actualGasPrice?: null,
      success?: null
    ): UserOperationEventEventFilter;
    UserOperationEvent(
      sender?: string | null,
      paymaster?: string | null,
      nonce?: null,
      actualGasCost?: null,
      actualGasPrice?: null,
      success?: null
    ): UserOperationEventEventFilter;

    "UserOperationRevertReason(address,uint256,bytes)"(
      sender?: string | null,
      nonce?: null,
      revertReason?: null
    ): UserOperationRevertReasonEventFilter;
    UserOperationRevertReason(
      sender?: string | null,
      nonce?: null,
      revertReason?: null
    ): UserOperationRevertReasonEventFilter;
  };

  estimateGas: {
    addDeposit(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addDepositTo(
      target: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addStake(
      _unstakeDelayBlocks: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    create2factory(overrides?: CallOverrides): Promise<BigNumber>;

    getPaymastersStake(
      paymasters: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSenderAddress(
      initCode: BytesLike,
      _salt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStakeInfo(
      paymaster: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    handleOp(
      op: UserOperationStruct,
      redeemer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    handleOps(
      ops: UserOperationStruct[],
      redeemer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    internalHandleOp(
      op: UserOperationStruct,
      context: BytesLike,
      preOpGas: BigNumberish,
      prefund: BigNumberish,
      paymentMode: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isContractDeployed(
      addr: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isPaymasterStaked(
      paymaster: string,
      stake: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isStaked(
      paymaster: string,
      requiredStake: BigNumberish,
      requiredDelayBlocks: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    paymasterStake(overrides?: CallOverrides): Promise<BigNumber>;

    simulatePaymasterValidation(
      userOp: UserOperationStruct,
      gasUsedByPayForSelfOp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    simulateValidation(
      userOp: UserOperationStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    simulateWalletValidation(
      userOp: UserOperationStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    stakes(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    unlockStake(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unstakeDelayBlocks(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawStake(
      withdrawAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addDeposit(
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addDepositTo(
      target: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addStake(
      _unstakeDelayBlocks: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    create2factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPaymastersStake(
      paymasters: string[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSenderAddress(
      initCode: BytesLike,
      _salt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStakeInfo(
      paymaster: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    handleOp(
      op: UserOperationStruct,
      redeemer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    handleOps(
      ops: UserOperationStruct[],
      redeemer: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    internalHandleOp(
      op: UserOperationStruct,
      context: BytesLike,
      preOpGas: BigNumberish,
      prefund: BigNumberish,
      paymentMode: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isContractDeployed(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isPaymasterStaked(
      paymaster: string,
      stake: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isStaked(
      paymaster: string,
      requiredStake: BigNumberish,
      requiredDelayBlocks: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    paymasterStake(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    simulatePaymasterValidation(
      userOp: UserOperationStruct,
      gasUsedByPayForSelfOp: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    simulateValidation(
      userOp: UserOperationStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    simulateWalletValidation(
      userOp: UserOperationStruct,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    stakes(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    unlockStake(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unstakeDelayBlocks(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdrawStake(
      withdrawAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
