/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type UserOperationStruct = {
  sender: string;
  nonce: BigNumberish;
  initCode: BytesLike;
  callData: BytesLike;
  callGas: BigNumberish;
  verificationGas: BigNumberish;
  preVerificationGas: BigNumberish;
  maxFeePerGas: BigNumberish;
  maxPriorityFeePerGas: BigNumberish;
  paymaster: string;
  paymasterData: BytesLike;
  signature: BytesLike;
};

export type UserOperationStructOutput = [
  string,
  BigNumber,
  string,
  string,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  string,
  string,
  string
] & {
  sender: string;
  nonce: BigNumber;
  initCode: string;
  callData: string;
  callGas: BigNumber;
  verificationGas: BigNumber;
  preVerificationGas: BigNumber;
  maxFeePerGas: BigNumber;
  maxPriorityFeePerGas: BigNumber;
  paymaster: string;
  paymasterData: string;
  signature: string;
};

export interface TestUtilInterface extends utils.Interface {
  functions: {
    "packUserOp((address,uint256,bytes,bytes,uint256,uint256,uint256,uint256,uint256,address,bytes,bytes))": FunctionFragment;
    "prefund((address,uint256,bytes,bytes,uint256,uint256,uint256,uint256,uint256,address,bytes,bytes))": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "packUserOp",
    values: [UserOperationStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "prefund",
    values: [UserOperationStruct]
  ): string;

  decodeFunctionResult(functionFragment: "packUserOp", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "prefund", data: BytesLike): Result;

  events: {};
}

export interface TestUtil extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TestUtilInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    packUserOp(
      op: UserOperationStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;

    prefund(
      op: UserOperationStruct,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  packUserOp(
    op: UserOperationStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  prefund(
    op: UserOperationStruct,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    packUserOp(
      op: UserOperationStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    prefund(
      op: UserOperationStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    packUserOp(
      op: UserOperationStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    prefund(
      op: UserOperationStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    packUserOp(
      op: UserOperationStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    prefund(
      op: UserOperationStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
